services:
  py311:
    build:
      context: ..
      dockerfile: entorno/Dockerfile
      args:
        PYTHON_VERSION: "3.11"
    container_name: tc_p1_py311
    volumes:
      - ..:/app
    command: pytest -q

  py312:
    build:
      context: ..
      dockerfile: entorno/Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    container_name: tc_p1_py312
    ports:
      - "8550:8550"
    volumes:
      - ..:/app

  py313:
    build:
      context: ..
      dockerfile: entorno/Dockerfile
      args:
        PYTHON_VERSION: "3.13"
    container_name: tc_p1_py313
    volumes:
      - ..:/app
    command: pytest -q
